"""empty message

Revision ID: 277e318c591d
Revises: 
Create Date: 2019-08-06 22:59:26.609952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277e318c591d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('created_time', sa.String(), nullable=True),
    sa.Column('received_time', sa.String(), nullable=True),
    sa.Column('subreddit', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('word', sa.String(), nullable=True),
    sa.Column('meaning', sa.String(), nullable=True),
    sa.Column('example', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    # ### end Alembic commands ###
